server:
  port: 8080
spring:
  application:
    name: "accounts"
  profiles:
    active: "prod"
  config:
    import: "optional:configserver:http://localhost:8071/"

  datasource:
    url: jdbc:mysql://localhost:3306/accountsdb
    username: root
    password: root
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      access: unrestricted
  info:
    env:
      enabled: true


eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 30       # Heartbeat every 30s (default)
    leaseExpirationDurationInSeconds: 90   # Expire after 90s of no heartbeat
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
    registryFetchIntervalSeconds: 30       # How often to fetch registry
    healthcheck:
      enabled: true                        # Use /actuator/health for status


info:
  app:
    name: "accounts"
    description: "Bank Accounts Application"
    version: "1.0.0"

logging:
  level:
    com:
      bank:
        accounts: DEBUG

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10   # this tells to make at try 10 request before going from closed to open circuit
      permittedNumberOfCallsInHalfOpenState: 2  # I want my circuit breaker pattern to try 2 request in the half open circuit state based on  response it will decide what to do whether go to closed state or go to full open state
      failureRateThreshold: 50  # if ate least 50 percent of the request are failed then move to open circuit state
      waitDurationInOpenState: 10000 # 10 sec

resilience4j.retry:
  configs:
    default:
      maxAttempts: 3
      waitDuration: 100
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2
      ignoreExceptions:
        -java.lang.NullPointerException
      retryExceptions:    #if I write this then I don't need to write ignore Exceptions
        -java.util.concurrent.TimeoutException